---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: stable
controlPlaneEndpoint: "100.100.100.10:6443"
etcd:
  external:
    endpoints:
      - https://100.100.100.17:2379
      - https://100.100.100.18:2379
      - https://100.100.100.19:2379
    caFile: /etc/kubernetes/pki/etcd/ca.pem
    certFile: /etc/kubernetes/pki/etcd/etcd.pem
    keyFile: /etc/kubernetes/pki/etcd/etcd-key.pem
