---
- hosts: your_target_hosts
  become: yes
  tasks:
    - name: Clone Kubernetes repository
      git:
        repo: https://github.com/nghiahl-sysadmin/kubernetes.git
        dest: /opt/kubernetes
        version: master
      register: git_clone

    - name: Run installation script
      command: chmod +x /opt/kubernetes/install_environment_kubernetes.sh && /opt/kubernetes/install_environment_kubernetes.sh
      when: git_clone.changed

    - name: Remove Kubernetes repository
      file:
        path: /opt/kubernetes
        state: absent
