- name: Install Environment for Multiple Kubernetes
  hosts: all
  become: true
  tasks:
    - name: Download bash script from github
      get_url:
        url: "https://raw.githubusercontent.com/nghiahl-sysadmin/kubernetes-v1.26.2-eol-2024-02-28/main/install_environment_kubernetes.sh"
        dest: "/tmp/install_environment_kubernetes.sh"
        mode: '0755'
        
    - name: Run bash script to install environment kubernetes
      command: "/tmp/install_environment_kubernetes.sh"
      
    - name: Remove bash script
      file:
        path: "/tmp/install_environment_kubernetes.sh"
        state: absent
